---
- name: Setup repositories
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars.yaml
  tasks:

  - name: Setup common tasks
    include_role:
      name: common
  
  
  - name: deploy haproxy
    include_role:
      name: haproxy
    when: "'frontends' in group_names"
  
  
  - name: deploy tomcat
    include_role:
      name: apps
    when: "'apps' in group_names"
  
  
  - name: deploy postgres
    include_role:
      name: appdb
    when: "'appdbs' in group_names"
